Testing docker again

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -74,20 +74,20 @@ jobs:
           if [[ ${BUILD_CHECK} == *"App initialized successfully"* ]]; then
             echo "Build passed!"
 
-            {
-              echo "### 🐳 Docker Images Test Results"
-              echo "The tests passed! 🎉🎉🎉"
-            } >> $GITHUB_STEP_SUMMARY
-
-            exit 0
+#            {
+#              echo "### 🐳 Docker Images Test Results"
+#              echo "The tests passed! 🎉🎉🎉"
+#            } >> $GITHUB_STEP_SUMMARY
+#
+#            exit 0
           else
             echo "Build failed! :("
-
-            {
-              echo "### 🐳 Docker Images Test Results"
-              echo "The tests failed! 😭😭😭"
-              echo "Please check the logs."
-            } >> $GITHUB_STEP_SUMMARY
-
-            exit 1
+#
+#            {
+#              echo "### 🐳 Docker Images Test Results"
+#              echo "The tests failed! 😭😭😭"
+#              echo "Please check the logs."
+#            } >> $GITHUB_STEP_SUMMARY
+#
+#            exit 1
           fi
