Why is this failing with no output?

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -71,23 +71,23 @@ jobs:
           echo "${BUILD_CHECK}"
           echo "-----------------"
 
-          if [[ ${BUILD_CHECK} == *"App initialized successfully"* ]]; then
-            echo "Build passed!"
-          
-            {
-              echo "### 🐳 Docker Images Test Results"
-              echo "The tests passed! 🎉🎉🎉"
-            } >> $GITHUB_STEP_SUMMARY
-
-            exit 0
-          else
-            echo "Build failed! :("
-          
-            {
-              echo "### 🐳 Docker Images Test Results"
-              echo "The tests failed! 😭😭😭"
-              echo "Please check the logs."
-            } >> $GITHUB_STEP_SUMMARY
-
-            exit 1
-          fi
+#          if [[ ${BUILD_CHECK} == *"App initialized successfully"* ]]; then
+#            echo "Build passed!"
+#
+#            {
+#              echo "### 🐳 Docker Images Test Results"
+#              echo "The tests passed! 🎉🎉🎉"
+#            } >> $GITHUB_STEP_SUMMARY
+#
+#            exit 0
+#          else
+#            echo "Build failed! :("
+#
+#            {
+#              echo "### 🐳 Docker Images Test Results"
+#              echo "The tests failed! 😭😭😭"
+#              echo "Please check the logs."
+#            } >> $GITHUB_STEP_SUMMARY
+#
+#            exit 1
+#          fi
