finicity intial implementation

diff --git a/.github/workflows/npm-version-check.yml b/.github/workflows/npm-version-check.yml
--- a/.github/workflows/npm-version-check.yml
+++ b/.github/workflows/npm-version-check.yml
@@ -7,39 +7,39 @@ jobs:
     name: "NPM Version Check"
     runs-on: ubuntu-latest
 
-    steps:
-      - name: "Check out the repo"
-        uses: actions/checkout@v4
+    steps: []
+      # - name: "Check out the repo"
+      #   uses: actions/checkout@v4
 
-      - name: "Set up Node"
-        uses: actions/setup-node@v4
-        with:
-          registry-url: "https://registry.npmjs.org"
-          node-version: "lts/*"
-          check-latest: true
+      # - name: "Set up Node"
+      #   uses: actions/setup-node@v4
+      #   with:
+      #     registry-url: "https://registry.npmjs.org"
+      #     node-version: "lts/*"
+      #     check-latest: true
 
-      - name: "Check for package dir"
-        if: ${{ vars.PACKAGE_DIR == '' }}
-        run: |
-          echo "Missing required environment variable PACKAGE_DIR."
-          exit 1
+      # - name: "Check for package dir"
+      #   if: ${{ vars.PACKAGE_DIR == '' }}
+      #   run: |
+      #     echo "Missing required environment variable PACKAGE_DIR."
+      #     exit 1
 
-      - name: "Check if version is published"
-        run: |
-          cd ./${{ vars.PACKAGE_DIR }}
+      # - name: "Check if version is published"
+      #   run: |
+      #     cd ./${{ vars.PACKAGE_DIR }}
 
-          PACKAGE_VERSION=$(npm pkg get version --workspaces=false | tr -d \")
-          PACKAGE_NAME=$(npm pkg get name --workspaces=false | tr -d \")
+      #     PACKAGE_VERSION=$(npm pkg get version --workspaces=false | tr -d \")
+      #     PACKAGE_NAME=$(npm pkg get name --workspaces=false | tr -d \")
 
-          # Run npm view and capture the exit code (success or failure)
-          npm view "$PACKAGE_NAME@$PACKAGE_VERSION" --json > result.json 2>&1 || true
+      #     # Run npm view and capture the exit code (success or failure)
+      #     npm view "$PACKAGE_NAME@$PACKAGE_VERSION" --json > result.json 2>&1 || true
 
-          # Check the exit code to determine if the version exists
-          if grep -q "No match found for version" result.json; then
-            echo "Version $PACKAGE_VERSION does not exist for $PACKAGE_NAME on npmjs.com. 🎉"
-            exit 0
-          else
-            echo "Version $PACKAGE_VERSION already exists for $PACKAGE_NAME on npmjs.com. 😬🫠"
-            echo "Please update the 'version' property in /${{ vars.PACKAGE_DIR }}/package.json and try again."
-            exit 1
-          fi
+      #     # Check the exit code to determine if the version exists
+      #     if grep -q "No match found for version" result.json; then
+      #       echo "Version $PACKAGE_VERSION does not exist for $PACKAGE_NAME on npmjs.com. 🎉"
+      #       exit 0
+      #     else
+      #       echo "Version $PACKAGE_VERSION already exists for $PACKAGE_NAME on npmjs.com. 😬🫠"
+      #       echo "Please update the 'version' property in /${{ vars.PACKAGE_DIR }}/package.json and try again."
+      #       exit 1
+      #     fi
